export const MOCK_CATEGORIES = [
  // --- КОПИЯ 1 (Оригинал) ---
  {
    id: "2",
    name: "Крупная бытовая техника",
    slug: "krupnaya",
    description: "Холодильники, стиральные машины, посудомоечные машины",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-02"),
    characteristics: [],
  },
  {
    id: "3",
    name: "Холодильники",
    slug: "kholodilniki",
    description: "Холодильники и морозильные камеры",
    image: null,
    icon: "refrigerator",
    parentId: "2",
    isActive: true,
    createdAt: new Date("2026-01-03"),
    characteristics: [
      { name: "Объём", unit: "л", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип", required: true },
      { name: "Количество камер", required: false },
    ],
  },
  {
    id: "4",
    name: "Стиральные машины",
    slug: "stiralnye-mashiny",
    description: "Стиральные машины и сушилки",
    image: null,
    icon: "washing-machine",
    parentId: "2",
    isActive: true,
    createdAt: new Date("2026-01-04"),
    characteristics: [
      { name: "Загрузка", unit: "кг", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип загрузки", required: true },
      { name: "Обороты отжима", required: false },
    ],
  },
  {
    id: "5",
    name: "Посудомоечные машины",
    slug: "posudomoechnye",
    description: "Посудомоечные машины",
    image: null,
    icon: "droplets",
    parentId: "2",
    isActive: true,
    createdAt: new Date("2026-01-05"),
    characteristics: [
      { name: "Загрузка", unit: "комплектов", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип сушки", required: false },
    ],
  },
  {
    id: "6",
    name: "Мелкая бытовая техника",
    slug: "melkaya",
    description: "Пылесосы, кофемашины, блендеры",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-06"),
    characteristics: [],
  },
  {
    id: "7",
    name: "Пылесосы",
    slug: "pylesosy",
    description: "Пылесосы для уборки",
    image: null,
    icon: "robot-vacuum",
    parentId: "6",
    isActive: true,
    createdAt: new Date("2026-01-07"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип уборки", required: false },
    ],
  },
  {
    id: "8",
    name: "Кофемашины",
    slug: "kofemashiny",
    description: "Кофемашины и кофеварки",
    image: null,
    icon: "coffee",
    parentId: "6",
    isActive: true,
    createdAt: new Date("2026-01-08"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Объём бака", unit: "мл", required: false },
    ],
  },
  {
    id: "9",
    name: "Блендеры",
    slug: "blendery",
    description: "Блендеры и кухонные комбайны",
    image: null,
    icon: "blender",
    parentId: "6",
    isActive: true,
    createdAt: new Date("2026-01-09"),
    characteristics: [
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип", required: true },
      { name: "Объём чаши", unit: "л", required: false },
    ],
  },
  {
    id: "10",
    name: "Климатическая техника",
    slug: "klimat",
    description: "Кондиционеры и обогреватели",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-10"),
    characteristics: [],
  },
  {
    id: "11",
    name: "Кондиционеры",
    slug: "konditsionery",
    description: "Кондиционеры и сплит-системы",
    image: null,
    icon: "fan",
    parentId: "10",
    isActive: true,
    createdAt: new Date("2026-01-11"),
    characteristics: [
      { name: "Мощность", unit: "BTU", required: true },
      { name: "Тип", required: true },
      { name: "Площадь помещения", unit: "м²", required: true },
    ],
  },
  {
    id: "12",
    name: "Обогреватели",
    slug: "obogrevateli",
    description: "Обогреватели и конвекторы",
    image: null,
    icon: "heater",
    parentId: "10",
    isActive: false,
    createdAt: new Date("2026-01-12"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Площадь обогрева", unit: "м²", required: false },
    ],
  },

  // --- КОПИЯ 2 ---
  {
    id: "102",
    name: "Крупная бытовая техника 2",
    slug: "krupnaya-2",
    description: "Холодильники, стиральные машины, посудомоечные машины",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-02"),
    characteristics: [],
  },
  {
    id: "103",
    name: "Холодильники 2",
    slug: "kholodilniki-2",
    description: "Холодильники и морозильные камеры",
    image: null,
    icon: "refrigerator",
    parentId: "102",
    isActive: true,
    createdAt: new Date("2026-01-03"),
    characteristics: [
      { name: "Объём", unit: "л", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип", required: true },
      { name: "Количество камер", required: false },
    ],
  },
  {
    id: "104",
    name: "Стиральные машины 2",
    slug: "stiralnye-mashiny-2",
    description: "Стиральные машины и сушилки",
    image: null,
    icon: "washing-machine",
    parentId: "102",
    isActive: true,
    createdAt: new Date("2026-01-04"),
    characteristics: [
      { name: "Загрузка", unit: "кг", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип загрузки", required: true },
      { name: "Обороты отжима", required: false },
    ],
  },
  {
    id: "105",
    name: "Посудомоечные машины 2",
    slug: "posudomoechnye-2",
    description: "Посудомоечные машины",
    image: null,
    icon: "droplets",
    parentId: "102",
    isActive: true,
    createdAt: new Date("2026-01-05"),
    characteristics: [
      { name: "Загрузка", unit: "комплектов", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип сушки", required: false },
    ],
  },
  {
    id: "106",
    name: "Мелкая бытовая техника 2",
    slug: "melkaya-2",
    description: "Пылесосы, кофемашины, блендеры",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-06"),
    characteristics: [],
  },
  {
    id: "107",
    name: "Пылесосы 2",
    slug: "pylesosy-2",
    description: "Пылесосы для уборки",
    image: null,
    icon: "robot-vacuum",
    parentId: "106",
    isActive: true,
    createdAt: new Date("2026-01-07"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип уборки", required: false },
    ],
  },
  {
    id: "108",
    name: "Кофемашины 2",
    slug: "kofemashiny-2",
    description: "Кофемашины и кофеварки",
    image: null,
    icon: "coffee",
    parentId: "106",
    isActive: true,
    createdAt: new Date("2026-01-08"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Объём бака", unit: "мл", required: false },
    ],
  },
  {
    id: "109",
    name: "Блендеры 2",
    slug: "blendery-2",
    description: "Блендеры и кухонные комбайны",
    image: null,
    icon: "blender",
    parentId: "106",
    isActive: true,
    createdAt: new Date("2026-01-09"),
    characteristics: [
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип", required: true },
      { name: "Объём чаши", unit: "л", required: false },
    ],
  },
  {
    id: "110",
    name: "Климатическая техника 2",
    slug: "klimat-2",
    description: "Кондиционеры и обогреватели",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-10"),
    characteristics: [],
  },
  {
    id: "111",
    name: "Кондиционеры 2",
    slug: "konditsionery-2",
    description: "Кондиционеры и сплит-системы",
    image: null,
    icon: "fan",
    parentId: "110",
    isActive: true,
    createdAt: new Date("2026-01-11"),
    characteristics: [
      { name: "Мощность", unit: "BTU", required: true },
      { name: "Тип", required: true },
      { name: "Площадь помещения", unit: "м²", required: true },
    ],
  },
  {
    id: "112",
    name: "Обогреватели 2",
    slug: "obogrevateli-2",
    description: "Обогреватели и конвекторы",
    image: null,
    icon: "heater",
    parentId: "110",
    isActive: false,
    createdAt: new Date("2026-01-12"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Площадь обогрева", unit: "м²", required: false },
    ],
  },

  // --- КОПИЯ 3 ---
  {
    id: "202",
    name: "Крупная бытовая техника 3",
    slug: "krupnaya-3",
    description: "Холодильники, стиральные машины, посудомоечные машины",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-02"),
    characteristics: [],
  },
  {
    id: "203",
    name: "Холодильники 3",
    slug: "kholodilniki-3",
    description: "Холодильники и морозильные камеры",
    image: null,
    icon: "refrigerator",
    parentId: "202",
    isActive: true,
    createdAt: new Date("2026-01-03"),
    characteristics: [
      { name: "Объём", unit: "л", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип", required: true },
      { name: "Количество камер", required: false },
    ],
  },
  {
    id: "204",
    name: "Стиральные машины 3",
    slug: "stiralnye-mashiny-3",
    description: "Стиральные машины и сушилки",
    image: null,
    icon: "washing-machine",
    parentId: "202",
    isActive: true,
    createdAt: new Date("2026-01-04"),
    characteristics: [
      { name: "Загрузка", unit: "кг", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип загрузки", required: true },
      { name: "Обороты отжима", required: false },
    ],
  },
  {
    id: "205",
    name: "Посудомоечные машины 3",
    slug: "posudomoechnye-3",
    description: "Посудомоечные машины",
    image: null,
    icon: "droplets",
    parentId: "202",
    isActive: true,
    createdAt: new Date("2026-01-05"),
    characteristics: [
      { name: "Загрузка", unit: "комплектов", required: true },
      { name: "Класс энергоэффективности", required: true },
      { name: "Тип сушки", required: false },
    ],
  },
  {
    id: "206",
    name: "Мелкая бытовая техника 3",
    slug: "melkaya-3",
    description: "Пылесосы, кофемашины, блендеры",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-06"),
    characteristics: [],
  },
  {
    id: "207",
    name: "Пылесосы 3",
    slug: "pylesosy-3",
    description: "Пылесосы для уборки",
    image: null,
    icon: "robot-vacuum",
    parentId: "206",
    isActive: true,
    createdAt: new Date("2026-01-07"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип уборки", required: false },
    ],
  },
  {
    id: "208",
    name: "Кофемашины 3",
    slug: "kofemashiny-3",
    description: "Кофемашины и кофеварки",
    image: null,
    icon: "coffee",
    parentId: "206",
    isActive: true,
    createdAt: new Date("2026-01-08"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Объём бака", unit: "мл", required: false },
    ],
  },
  {
    id: "209",
    name: "Блендеры 3",
    slug: "blendery-3",
    description: "Блендеры и кухонные комбайны",
    image: null,
    icon: "blender",
    parentId: "206",
    isActive: true,
    createdAt: new Date("2026-01-09"),
    characteristics: [
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Тип", required: true },
      { name: "Объём чаши", unit: "л", required: false },
    ],
  },
  {
    id: "210",
    name: "Климатическая техника 3",
    slug: "klimat-3",
    description: "Кондиционеры и обогреватели",
    image: null,
    icon: "",
    parentId: null,
    isActive: true,
    createdAt: new Date("2026-01-10"),
    characteristics: [],
  },
  {
    id: "211",
    name: "Кондиционеры 3",
    slug: "konditsionery-3",
    description: "Кондиционеры и сплит-системы",
    image: null,
    icon: "fan",
    parentId: "210",
    isActive: true,
    createdAt: new Date("2026-01-11"),
    characteristics: [
      { name: "Мощность", unit: "BTU", required: true },
      { name: "Тип", required: true },
      { name: "Площадь помещения", unit: "м²", required: true },
    ],
  },
  {
    id: "212",
    name: "Обогреватели 3",
    slug: "obogrevateli-3",
    description: "Обогреватели и конвекторы",
    image: null,
    icon: "heater",
    parentId: "210",
    isActive: false,
    createdAt: new Date("2026-01-12"),
    characteristics: [
      { name: "Тип", required: true },
      { name: "Мощность", unit: "Вт", required: true },
      { name: "Площадь обогрева", unit: "м²", required: false },
    ],
  },
];
